### ISSUE TITLE
Consolidate Extended Types

### ISSUE THREAD

**Issue by fchorney** [cjdoris/Infinity.jl#15]
As per this comment: https://github.com/cjdoris/Infinity.jl/pull/10#issuecomment-639109854
A few of the extended types functions could be put into an "infextendedcommon" sub folder so that we don't have as much code duplication. 

I'd like to open up a PR that attempts to remove as much code duplication from the different types.

**Comment by cjdoris** [comment]
Sounds good. This will make adding new types easier for #14.
