### ISSUE TITLE
Restructure code

### ISSUE THREAD

**Issue by cjdoris** [cjdoris/Infinity.jl#5]
Separate out the code for `Infinite` and `InfExtended` (and the future `InfExtendedTime`) into separate files, something like:

```
InfExtended.jl
utils.jl
infinite/
  base.jl
  io.jl
  ...
infextended/
  base.jl
  io.jl
  ...
infextendedtime/
  ...
```

**Comment by fchorney** [comment]
Hey, just wondering if you were going to tackle this issue (I assume so since you assigned yourself). I possibly have some time to try and get this done myself, as it would be nice to have for #3.

**Comment by cjdoris** [comment]
Be my guest!
